syntax = "proto3";

package atk_hub;

import "dpi_led.proto";
import "mouse_info.proto";
import "performance.proto";
import "profiles.proto";
import "silent_height.proto";

message Empty {}

message BatteryStatusResponse {
  int32 battery_level = 1;
}

message FarDistanceModeRequest {
  bool enabled = 1;
}

message FarDistanceModeResponse {
  bool enabled = 1;
}

service AtkHub {
  // Battery related methods
  rpc GetBatteryStatus(Empty) returns (BatteryStatusResponse);

  // LED effect methods
  rpc GetLedEffect(Empty) returns (LedEffectResponse);
  rpc SetLedEffect(LedEffectRequest) returns (LedEffectResponse);

  // Mouse info methods
  rpc GetMouseVersion(Empty) returns (MouseVersionResponse);
  rpc GetConnectionType(Empty) returns (ConnectionTypeResponse);
  rpc SetPollRate(PollRateRequest) returns (PollRateResponse);
  rpc GetPollRate(Empty) returns (PollRateResponse);

  // Performance settings
  rpc GetMousePerformance(Empty) returns (MousePerformanceResponse);
  rpc SetMousePerformance(MousePerformanceRequest) returns (MousePerformanceResponse);
  rpc GetSensorPerformance(Empty) returns (SensorPerformanceResponse);
  rpc SetSensorPerformance(SensorPerformanceRequest) returns (SensorPerformanceResponse);

  // Profile management
  rpc GetDpiProfiles(Empty) returns (GetProfilesResponse);
  rpc SetDpiProfile(UpdateGearRequest) returns (Profile);
  rpc NewDpiProfile(NewGearRequest) returns (Profile);
  rpc DeleteDpiProfile(DeleteGearRequest) returns (Empty);

  // Factory reset
  rpc FactoryReset(Empty) returns (Empty);

  // Far distance mode
  rpc GetFarDistanceMode(Empty) returns (FarDistanceModeResponse);
  rpc SetFarDistanceMode(FarDistanceModeRequest) returns (FarDistanceModeResponse);

  // Silent height
  rpc GetSilentHeight(Empty) returns (SilentHeightResponse);
  rpc SetSilentHeight(SilentHeightRequest) returns (SilentHeightResponse);
}
