syntax = "proto3";

package atk_hub;

message Color {
  int32 red = 1;
  int32 green = 2;
  int32 blue = 3;
}

enum DpiPreset {
  DpiPresetInvalid = 0;
  DpiPresetPreset1 = 1;
  DpiPresetPreset2 = 2;
  DpiPresetPreset3 = 3;
  DpiPresetPreset4 = 4;
  DpiPresetPreset5 = 5;
  DpiPresetPreset6 = 6;
  DpiPresetPreset7 = 7;
  DpiPresetPreset8 = 8;
}

message SetDpiProfileRequest {
  DpiPreset preset = 1;
  int32 dpi = 2;
}

message SetDpiProfileResponse {
  DpiPreset preset = 1;
  int32 dpi = 2;
}

message SetDpiProfileColorRequest {
  DpiPreset preset = 1;
  Color color = 2;
}

message SetDpiProfileColorResponse {
  DpiPreset preset = 1;
  Color color = 2;
}

message NewDpiProfileRequest {
  int32 dpi = 1;
  Color color = 2;
}

message NewDpiProfileResponse {
  DpiPreset preset = 1;
  int32 dpi = 2;
  Color color = 3;
}

message DeleteDpiProfileRequest {
  DpiPreset preset = 1;
}

message DeleteDpiProfileResponse {
  int32 remaining_profiles = 1;
}

message DpiProfile {
  DpiPreset preset = 1;
  int32 dpi = 2;
  Color color = 3;
}

message GetDpiProfilesResponse {
  repeated DpiProfile profiles = 1;
}
